[providers.op]
type = "1password"
vault = "Personal"

[secrets]
ATUIN_USERNAME = { provider = "op", value = "Atuin/username" }
ATUIN_PASSWORD = { provider = "op", value = "Atuin/password" }
ATUIN_KEY = { provider = "op", value = "Atuin/key" }
CONTEXT7_API_KEY = { provider = "op", value = "Context7/apikey" }
